-- ORMEN Atelier: MISSO fabrics from photos. GENERATED by scripts/build-photo-fabrics-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run (after all migrations).
-- Codes follow the order the photos were sent in; colour names and the scale are provisional
-- (see lib/seed/photo-fabrics.ts) and can be changed in the panel. Width, pattern repeat and
-- cut direction are left empty on purpose: they are not known yet.

insert into public.fabrics (code, series, color_name, color_family, type, description, pattern, is_active, is_placeholder, sort_order) values
  ('MISSO-01', 'MISSO', 'Mercan Çok Renkli', 'kirmizi-bordo', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 100),
  ('MISSO-02', 'MISSO', 'Gri Bej', 'gri', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 101),
  ('MISSO-03', 'MISSO', 'Siyah Pembe', 'pembe', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 102),
  ('MISSO-04', 'MISSO', 'Kahve Altın', 'kahve', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 103),
  ('MISSO-05', 'MISSO', 'Gri Pastel', 'gri', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 104)
on conflict (code) do nothing;

insert into public.fabric_textures (fabric_id, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color, derived_maps)
select f.id, v.albedo_1k, v.albedo_2k, v.normal_1k, v.normal_2k, v.roughness_1k, v.roughness_2k, v.thumb, v.repeat_w_cm, v.repeat_h_cm, v.avg_color, true
from (values
  ('MISSO-01', '/seed/fabrics/misso/misso-01-albedo-1k.webp', '/seed/fabrics/misso/misso-01-albedo-2k.webp', '/seed/fabrics/misso/misso-01-normal-1k.webp', '/seed/fabrics/misso/misso-01-normal-2k.webp', '/seed/fabrics/misso/misso-01-roughness-1k.webp', '/seed/fabrics/misso/misso-01-roughness-2k.webp', '/seed/fabrics/misso/misso-01-thumb.webp', 22.8, 22.8, '#A7988F'),
  ('MISSO-02', '/seed/fabrics/misso/misso-02-albedo-1k.webp', '/seed/fabrics/misso/misso-02-albedo-2k.webp', '/seed/fabrics/misso/misso-02-normal-1k.webp', '/seed/fabrics/misso/misso-02-normal-2k.webp', '/seed/fabrics/misso/misso-02-roughness-1k.webp', '/seed/fabrics/misso/misso-02-roughness-2k.webp', '/seed/fabrics/misso/misso-02-thumb.webp', 23.7, 26.3, '#9E9692'),
  ('MISSO-03', '/seed/fabrics/misso/misso-03-albedo-1k.webp', '/seed/fabrics/misso/misso-03-albedo-2k.webp', '/seed/fabrics/misso/misso-03-normal-1k.webp', '/seed/fabrics/misso/misso-03-normal-2k.webp', '/seed/fabrics/misso/misso-03-roughness-1k.webp', '/seed/fabrics/misso/misso-03-roughness-2k.webp', '/seed/fabrics/misso/misso-03-thumb.webp', 43.1, 37.3, '#8B6B66'),
  ('MISSO-04', '/seed/fabrics/misso/misso-04-albedo-1k.webp', '/seed/fabrics/misso/misso-04-albedo-2k.webp', '/seed/fabrics/misso/misso-04-normal-1k.webp', '/seed/fabrics/misso/misso-04-normal-2k.webp', '/seed/fabrics/misso/misso-04-roughness-1k.webp', '/seed/fabrics/misso/misso-04-roughness-2k.webp', '/seed/fabrics/misso/misso-04-thumb.webp', 34.2, 32.7, '#7B695D'),
  ('MISSO-05', '/seed/fabrics/misso/misso-05-albedo-1k.webp', '/seed/fabrics/misso/misso-05-albedo-2k.webp', '/seed/fabrics/misso/misso-05-normal-1k.webp', '/seed/fabrics/misso/misso-05-normal-2k.webp', '/seed/fabrics/misso/misso-05-roughness-1k.webp', '/seed/fabrics/misso/misso-05-roughness-2k.webp', '/seed/fabrics/misso/misso-05-thumb.webp', 44.2, 55.5, '#98857E')
) as v (code, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color)
join public.fabrics f on f.code = v.code
on conflict (fabric_id) do nothing;
