-- ORMEN Atelier: Chester showcase models. GENERATED by scripts/build-showcase-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run. Run supabase/kumaslar-misso.sql first (default fabrics).
-- Running it again changes nothing: existing models are skipped.

insert into public.models (firm_id, slug, name, procedural_key, params, fabric_material_names, width_cm, depth_cm, height_cm, default_fabric_code, is_active, sort_order)
select null, v.slug, v.name, 'parametric', v.params::jsonb, string_to_array(v.materials, ','), v.w, v.d, v.h, v.fabric, v.active, v.sort_order
from (values
  ('chester-kanepe', 'Chester Kanepe', '{"tip":"uclu","kol":"kivrik","sirt":"alcak","ayak":"konik","genislikCm":220,"derinlikCm":92,"sirtTipi":"kapitone","yukseklikCm":76}', 'kumas', 220, 92, 76, 'MISSO-06', true, 3),
  ('chester-berjer', 'Kulaklı Chester Berjer', '{"tip":"berjer","kol":"kivrik","sirt":"alcak","ayak":"konik","genislikCm":82,"derinlikCm":88,"sirtTipi":"kapitone","kulak":true,"yukseklikCm":104}', 'kumas', 82, 88, 104, 'MISSO-03', true, 4)
) as v (slug, name, params, materials, w, d, h, fabric, active, sort_order)
where not exists (select 1 from public.models m where m.firm_id is null and m.slug = v.slug);
