-- ORMEN Atelier: demo catalogue. GENERATED by scripts/build-seed-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor after the migration and press Run.
-- Fabrics are placeholders (is_placeholder = true): their images are code-generated
-- and served by the site from /seed/. Technical values are intentionally empty.
-- Running it again changes nothing: existing rows are skipped.

insert into public.fabrics (code, series, color_name, color_family, type, description, is_active, is_placeholder, sort_order) values
  ('LUMA-01', 'LUMA', 'Kırık Beyaz', 'beyaz-krem', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 0),
  ('LUMA-02', 'LUMA', 'Kum', 'bej-kum', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 1),
  ('LUMA-03', 'LUMA', 'Vizon', 'bej-kum', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 2),
  ('LUMA-04', 'LUMA', 'Adaçayı', 'yesil', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 3),
  ('LUMA-05', 'LUMA', 'Karamel', 'kahve', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 4),
  ('LUMA-06', 'LUMA', 'Antrasit', 'antrasit-siyah', 'bukle', 'İri ilmekli, yumuşak tutumlu bukle.', true, true, 5),
  ('SIENA-01', 'SIENA', 'Krem', 'beyaz-krem', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 6),
  ('SIENA-02', 'SIENA', 'Taş', 'gri', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 7),
  ('SIENA-03', 'SIENA', 'Zeytin', 'yesil', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 8),
  ('SIENA-04', 'SIENA', 'Hardal', 'sari-hardal', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 9),
  ('SIENA-05', 'SIENA', 'Kiremit', 'turuncu-kiremit', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 10),
  ('SIENA-06', 'SIENA', 'Lacivert', 'mavi', 'dokuma', 'Melanj iplikli, düz örgü dokuma.', true, true, 11),
  ('PIETRA-01', 'PIETRA', 'Kum', 'bej-kum', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 12),
  ('PIETRA-02', 'PIETRA', 'Pudra', 'pembe', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 13),
  ('PIETRA-03', 'PIETRA', 'Toprak', 'kahve', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 14),
  ('PIETRA-04', 'PIETRA', 'Füme', 'gri', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 15),
  ('PIETRA-05', 'PIETRA', 'Bordo', 'kirmizi-bordo', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 16),
  ('PIETRA-06', 'PIETRA', 'Gece Mavisi', 'mavi', 'nubuk', 'Mat, ince tüylü nubuk dokulu kumaş.', true, true, 17),
  ('VERSO-01', 'VERSO', 'Ekru', 'beyaz-krem', 'dokuma', 'İki renk iplikle balıksırtı örgü.', true, true, 18),
  ('VERSO-02', 'VERSO', 'Gri', 'gri', 'dokuma', 'İki renk iplikle balıksırtı örgü.', true, true, 19),
  ('VERSO-03', 'VERSO', 'Kahve', 'kahve', 'dokuma', 'İki renk iplikle balıksırtı örgü.', true, true, 20),
  ('VERSO-04', 'VERSO', 'Orman', 'yesil', 'dokuma', 'İki renk iplikle balıksırtı örgü.', true, true, 21),
  ('VERSO-05', 'VERSO', 'Antrasit', 'antrasit-siyah', 'dokuma', 'İki renk iplikle balıksırtı örgü.', true, true, 22)
on conflict (code) do nothing;

insert into public.fabric_textures (fabric_id, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color, derived_maps)
select f.id, v.albedo_1k, v.albedo_2k, v.normal_1k, v.normal_2k, v.roughness_1k, v.roughness_2k, v.thumb, v.repeat_w_cm, v.repeat_h_cm, v.avg_color, false
from (values
  ('LUMA-01', '/seed/fabrics/luma/luma-01-albedo-1k.webp', '/seed/fabrics/luma/luma-01-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-01-thumb.webp', 12, 12, '#E6DFD1'),
  ('LUMA-02', '/seed/fabrics/luma/luma-02-albedo-1k.webp', '/seed/fabrics/luma/luma-02-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-02-thumb.webp', 12, 12, '#C9B597'),
  ('LUMA-03', '/seed/fabrics/luma/luma-03-albedo-1k.webp', '/seed/fabrics/luma/luma-03-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-03-thumb.webp', 12, 12, '#9D8C7B'),
  ('LUMA-04', '/seed/fabrics/luma/luma-04-albedo-1k.webp', '/seed/fabrics/luma/luma-04-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-04-thumb.webp', 12, 12, '#8C957F'),
  ('LUMA-05', '/seed/fabrics/luma/luma-05-albedo-1k.webp', '/seed/fabrics/luma/luma-05-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-05-thumb.webp', 12, 12, '#A47248'),
  ('LUMA-06', '/seed/fabrics/luma/luma-06-albedo-1k.webp', '/seed/fabrics/luma/luma-06-albedo-2k.webp', '/seed/fabrics/luma/normal-1k.webp', '/seed/fabrics/luma/normal-2k.webp', '/seed/fabrics/luma/roughness-1k.webp', '/seed/fabrics/luma/roughness-2k.webp', '/seed/fabrics/luma/luma-06-thumb.webp', 12, 12, '#4A4844'),
  ('SIENA-01', '/seed/fabrics/siena/siena-01-albedo-1k.webp', '/seed/fabrics/siena/siena-01-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-01-thumb.webp', 8, 8, '#E2D9C7'),
  ('SIENA-02', '/seed/fabrics/siena/siena-02-albedo-1k.webp', '/seed/fabrics/siena/siena-02-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-02-thumb.webp', 8, 8, '#B1A898'),
  ('SIENA-03', '/seed/fabrics/siena/siena-03-albedo-1k.webp', '/seed/fabrics/siena/siena-03-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-03-thumb.webp', 8, 8, '#6B6A45'),
  ('SIENA-04', '/seed/fabrics/siena/siena-04-albedo-1k.webp', '/seed/fabrics/siena/siena-04-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-04-thumb.webp', 8, 8, '#BA8D36'),
  ('SIENA-05', '/seed/fabrics/siena/siena-05-albedo-1k.webp', '/seed/fabrics/siena/siena-05-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-05-thumb.webp', 8, 8, '#A3583A'),
  ('SIENA-06', '/seed/fabrics/siena/siena-06-albedo-1k.webp', '/seed/fabrics/siena/siena-06-albedo-2k.webp', '/seed/fabrics/siena/normal-1k.webp', '/seed/fabrics/siena/normal-2k.webp', '/seed/fabrics/siena/roughness-1k.webp', '/seed/fabrics/siena/roughness-2k.webp', '/seed/fabrics/siena/siena-06-thumb.webp', 8, 8, '#2F3A50'),
  ('PIETRA-01', '/seed/fabrics/pietra/pietra-01-albedo-1k.webp', '/seed/fabrics/pietra/pietra-01-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-01-thumb.webp', 15, 15, '#C7AF90'),
  ('PIETRA-02', '/seed/fabrics/pietra/pietra-02-albedo-1k.webp', '/seed/fabrics/pietra/pietra-02-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-02-thumb.webp', 15, 15, '#CFAEA2'),
  ('PIETRA-03', '/seed/fabrics/pietra/pietra-03-albedo-1k.webp', '/seed/fabrics/pietra/pietra-03-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-03-thumb.webp', 15, 15, '#7A5540'),
  ('PIETRA-04', '/seed/fabrics/pietra/pietra-04-albedo-1k.webp', '/seed/fabrics/pietra/pietra-04-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-04-thumb.webp', 15, 15, '#5F5E5A'),
  ('PIETRA-05', '/seed/fabrics/pietra/pietra-05-albedo-1k.webp', '/seed/fabrics/pietra/pietra-05-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-05-thumb.webp', 15, 15, '#6B2B2F'),
  ('PIETRA-06', '/seed/fabrics/pietra/pietra-06-albedo-1k.webp', '/seed/fabrics/pietra/pietra-06-albedo-2k.webp', '/seed/fabrics/pietra/normal-1k.webp', '/seed/fabrics/pietra/normal-2k.webp', '/seed/fabrics/pietra/roughness-1k.webp', '/seed/fabrics/pietra/roughness-2k.webp', '/seed/fabrics/pietra/pietra-06-thumb.webp', 15, 15, '#2C3444'),
  ('VERSO-01', '/seed/fabrics/verso/verso-01-albedo-1k.webp', '/seed/fabrics/verso/verso-01-albedo-2k.webp', '/seed/fabrics/verso/normal-1k.webp', '/seed/fabrics/verso/normal-2k.webp', '/seed/fabrics/verso/roughness-1k.webp', '/seed/fabrics/verso/roughness-2k.webp', '/seed/fabrics/verso/verso-01-thumb.webp', 9.6, 9.6, '#D9D0BE'),
  ('VERSO-02', '/seed/fabrics/verso/verso-02-albedo-1k.webp', '/seed/fabrics/verso/verso-02-albedo-2k.webp', '/seed/fabrics/verso/normal-1k.webp', '/seed/fabrics/verso/normal-2k.webp', '/seed/fabrics/verso/roughness-1k.webp', '/seed/fabrics/verso/roughness-2k.webp', '/seed/fabrics/verso/verso-02-thumb.webp', 9.6, 9.6, '#8D8B86'),
  ('VERSO-03', '/seed/fabrics/verso/verso-03-albedo-1k.webp', '/seed/fabrics/verso/verso-03-albedo-2k.webp', '/seed/fabrics/verso/normal-1k.webp', '/seed/fabrics/verso/normal-2k.webp', '/seed/fabrics/verso/roughness-1k.webp', '/seed/fabrics/verso/roughness-2k.webp', '/seed/fabrics/verso/verso-03-thumb.webp', 9.6, 9.6, '#5E4636'),
  ('VERSO-04', '/seed/fabrics/verso/verso-04-albedo-1k.webp', '/seed/fabrics/verso/verso-04-albedo-2k.webp', '/seed/fabrics/verso/normal-1k.webp', '/seed/fabrics/verso/normal-2k.webp', '/seed/fabrics/verso/roughness-1k.webp', '/seed/fabrics/verso/roughness-2k.webp', '/seed/fabrics/verso/verso-04-thumb.webp', 9.6, 9.6, '#3F4C3B'),
  ('VERSO-05', '/seed/fabrics/verso/verso-05-albedo-1k.webp', '/seed/fabrics/verso/verso-05-albedo-2k.webp', '/seed/fabrics/verso/normal-1k.webp', '/seed/fabrics/verso/normal-2k.webp', '/seed/fabrics/verso/roughness-1k.webp', '/seed/fabrics/verso/roughness-2k.webp', '/seed/fabrics/verso/verso-05-thumb.webp', 9.6, 9.6, '#3A3937')
) as v (code, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color)
join public.fabrics f on f.code = v.code
on conflict (fabric_id) do nothing;

insert into public.models (firm_id, slug, name, procedural_key, fabric_material_names, width_cm, depth_cm, height_cm, default_fabric_code, is_active, sort_order)
select null, v.slug, v.name, v.procedural_key, string_to_array(v.materials, ','), v.w, v.d, v.h, v.fabric, v.active, v.sort_order
from (values
  ('moduler-kanepe', 'Modüler Kanepe', 'modular-sofa', 'kumas', 238, 96, 85, 'LUMA-02', true, 0),
  ('berjer', 'Berjer', 'armchair', 'kumas', 81, 84, 94, 'SIENA-04', true, 1)
) as v (slug, name, procedural_key, materials, w, d, h, fabric, active, sort_order)
where not exists (select 1 from public.models m where m.firm_id is null and m.slug = v.slug);

-- a sample firm page (/f/ornek-mobilya) with a placeholder logo
insert into public.firms (name, slug, logo_path, accent_color, whatsapp, is_active) values
  ('Örnek Mobilya', 'ornek-mobilya', '/seed/firms/ornek-mobilya.svg', '#1F4E4A', null, true)
on conflict (slug) do nothing;
