-- ORMEN Atelier: MISSO fabrics from photos. GENERATED by scripts/build-photo-fabrics-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run (after all migrations).
-- Running it again is safe: fabric rows (codes, names edited in the panel) stay as they are,
-- images and scale are updated to this version. Scale is from a ruler photo (one zigzag tooth
-- 4.6 cm). Colour names are provisional; width, pattern repeat and cut direction are left empty
-- on purpose: they are not known yet.

insert into public.fabrics (code, series, color_name, color_family, type, description, pattern, is_active, is_placeholder, sort_order) values
  ('MISSO-01', 'MISSO', 'Mercan Çok Renkli', 'kirmizi-bordo', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 100),
  ('MISSO-02', 'MISSO', 'Gri Bej', 'gri', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 101),
  ('MISSO-03', 'MISSO', 'Siyah Pembe', 'pembe', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 102),
  ('MISSO-04', 'MISSO', 'Kahve Altın', 'kahve', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 103),
  ('MISSO-05', 'MISSO', 'Gri Pastel', 'gri', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 104),
  ('MISSO-06', 'MISSO', 'Gri Siyah', 'gri', 'jakar', 'Çok renkli zikzak desenli jakar.', 'desenli', true, false, 105)
on conflict (code) do nothing;

insert into public.fabric_textures (fabric_id, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color, derived_maps)
select f.id, v.albedo_1k, v.albedo_2k, v.normal_1k, v.normal_2k, v.roughness_1k, v.roughness_2k, v.thumb, v.repeat_w_cm, v.repeat_h_cm, v.avg_color, true
from (values
  ('MISSO-01', '/seed/fabrics/misso/misso-01-albedo-1k.webp', '/seed/fabrics/misso/misso-01-albedo-2k.webp', '/seed/fabrics/misso/misso-01-normal-1k.webp', '/seed/fabrics/misso/misso-01-normal-2k.webp', '/seed/fabrics/misso/misso-01-roughness-1k.webp', '/seed/fabrics/misso/misso-01-roughness-2k.webp', '/seed/fabrics/misso/misso-01-thumb.webp', 18.4, 112.5, '#A8998D'),
  ('MISSO-02', '/seed/fabrics/misso/misso-02-albedo-1k.webp', '/seed/fabrics/misso/misso-02-albedo-2k.webp', '/seed/fabrics/misso/misso-02-normal-1k.webp', '/seed/fabrics/misso/misso-02-normal-2k.webp', '/seed/fabrics/misso/misso-02-roughness-1k.webp', '/seed/fabrics/misso/misso-02-roughness-2k.webp', '/seed/fabrics/misso/misso-02-thumb.webp', 18.4, 87.2, '#A59A91'),
  ('MISSO-03', '/seed/fabrics/misso/misso-03-albedo-1k.webp', '/seed/fabrics/misso/misso-03-albedo-2k.webp', '/seed/fabrics/misso/misso-03-normal-1k.webp', '/seed/fabrics/misso/misso-03-normal-2k.webp', '/seed/fabrics/misso/misso-03-roughness-1k.webp', '/seed/fabrics/misso/misso-03-roughness-2k.webp', '/seed/fabrics/misso/misso-03-thumb.webp', 18.4, 26.8, '#8A6864'),
  ('MISSO-04', '/seed/fabrics/misso/misso-04-albedo-1k.webp', '/seed/fabrics/misso/misso-04-albedo-2k.webp', '/seed/fabrics/misso/misso-04-normal-1k.webp', '/seed/fabrics/misso/misso-04-normal-2k.webp', '/seed/fabrics/misso/misso-04-roughness-1k.webp', '/seed/fabrics/misso/misso-04-roughness-2k.webp', '/seed/fabrics/misso/misso-04-thumb.webp', 18.4, 99.4, '#7E736B'),
  ('MISSO-05', '/seed/fabrics/misso/misso-05-albedo-1k.webp', '/seed/fabrics/misso/misso-05-albedo-2k.webp', '/seed/fabrics/misso/misso-05-normal-1k.webp', '/seed/fabrics/misso/misso-05-normal-2k.webp', '/seed/fabrics/misso/misso-05-roughness-1k.webp', '/seed/fabrics/misso/misso-05-roughness-2k.webp', '/seed/fabrics/misso/misso-05-thumb.webp', 18.4, 91.5, '#A18C78'),
  ('MISSO-06', '/seed/fabrics/misso/misso-06-albedo-1k.webp', '/seed/fabrics/misso/misso-06-albedo-2k.webp', '/seed/fabrics/misso/misso-06-normal-1k.webp', '/seed/fabrics/misso/misso-06-normal-2k.webp', '/seed/fabrics/misso/misso-06-roughness-1k.webp', '/seed/fabrics/misso/misso-06-roughness-2k.webp', '/seed/fabrics/misso/misso-06-thumb.webp', 18.4, 112.5, '#A19991')
) as v (code, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color)
join public.fabrics f on f.code = v.code
on conflict (fabric_id) do update set
  albedo_1k = excluded.albedo_1k, albedo_2k = excluded.albedo_2k, normal_1k = excluded.normal_1k, normal_2k = excluded.normal_2k,
  roughness_1k = excluded.roughness_1k, roughness_2k = excluded.roughness_2k, thumb = excluded.thumb,
  repeat_w_cm = excluded.repeat_w_cm, repeat_h_cm = excluded.repeat_h_cm, avg_color = excluded.avg_color;
