-- ORMEN Atelier: showcase models (Chester, modern, İskandinav, köşe, U, blok, puf). GENERATED by scripts/build-showcase-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run. Run supabase/veri/2-kumaslar-misso.sql first (default fabrics).
-- Running it again changes nothing: existing models are skipped.

insert into public.models (firm_id, slug, name, procedural_key, params, fabric_material_names, width_cm, depth_cm, height_cm, default_fabric_code, is_active, sort_order)
select null, v.slug, v.name, 'parametric', v.params::jsonb, string_to_array(v.materials, ','), v.w, v.d, v.h, v.fabric, v.active, v.sort_order
from (values
  ('chester-kanepe', 'Chester Kanepe', '{"tip":"uclu","kol":"kivrik","sirt":"alcak","ayak":"konik","genislikCm":220,"derinlikCm":92,"sirtTipi":"kapitone","yukseklikCm":76}', 'kumas', 220, 92, 76, 'MISSO-06', true, 3),
  ('chester-berjer', 'Kulaklı Chester Berjer', '{"tip":"berjer","kol":"kivrik","sirt":"alcak","ayak":"konik","genislikCm":82,"derinlikCm":88,"sirtTipi":"kapitone","kulak":true,"yukseklikCm":104}', 'kumas', 82, 88, 104, 'MISSO-03', true, 4),
  ('modern-uclu', 'Modern Üçlü', '{"tip":"uclu","kol":"ince","sirt":"orta","ayak":"metal","genislikCm":232,"derinlikCm":96,"oturumTipi":"tek","yukseklikCm":80}', 'kumas', 232, 96, 80, 'SIENA-02', true, 5),
  ('iskandinav-ikili', 'İskandinav İkili', '{"tip":"ikili","kol":"yuvarlak","sirt":"orta","ayak":"konik","genislikCm":176,"derinlikCm":88,"yukseklikCm":84}', 'kumas', 176, 88, 84, 'LUMA-04', true, 6),
  ('sezlonglu-kose', 'Şezlonglu L Köşe', '{"tip":"kose","kol":"ince","sirt":"orta","ayak":"metal","genislikCm":286,"derinlikCm":98,"solUc":"kol","sagUc":"sezlong","solBoyCm":160,"sagBoyCm":168,"oturumTipi":"tek","yukseklikCm":80}', 'kumas', 286, 168, 80, 'PIETRA-04', true, 7),
  ('u-koltuk', 'U Koltuk', '{"tip":"kose","kol":"kalin","sirt":"alcak","ayak":"gizli","genislikCm":340,"derinlikCm":100,"solUc":"kose","sagUc":"kose","solBoyCm":230,"sagBoyCm":230,"sirtTipi":"sabit","yukseklikCm":78}', 'kumas', 340, 230, 78, 'LUMA-02', true, 8),
  ('blok-dortlu', 'Blok Dörtlü Kanepe', '{"tip":"dortlu","kol":"kalin","sirt":"alcak","ayak":"gizli","genislikCm":300,"derinlikCm":104,"sirtTipi":"sabit","yukseklikCm":74}', 'kumas', 300, 104, 74, 'VERSO-03', true, 9),
  ('puf', 'Puf', '{"tip":"puf","kol":"yok","sirt":"alcak","ayak":"konik","genislikCm":90,"derinlikCm":60,"yukseklikCm":42}', 'kumas', 90, 60, 42, 'SIENA-05', true, 10)
) as v (slug, name, params, materials, w, d, h, fabric, active, sort_order)
where not exists (select 1 from public.models m where m.firm_id is null and m.slug = v.slug);
