// Writes supabase/seed.sql: the demo catalogue (placeholder fabrics, the
// two code-generated models and a sample firm) as plain SQL, so it can be pasted into the
// Supabase SQL editor without installing anything. Safe to run twice.
//
//   npm run seed:sql

import { writeFileSync } from "node:fs";
import path from "node:path";
import { buildSeedFabrics } from "../lib/seed/fabrics";
import { SEED_FIRMS, SEED_MODELS } from "../lib/seed/models";

const q = (v: string | number | boolean | null | undefined): string =>
  v === null || v === undefined ? "null" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);
const row = (vals: (string | number | boolean | null | undefined)[]) => `  (${vals.map(q).join(", ")})`;

const fabrics = buildSeedFabrics();

const sql = `-- ORMEN Atelier: demo catalogue. GENERATED by scripts/build-seed-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor after the migration and press Run.
-- Fabrics are placeholders (is_placeholder = true): their images are code-generated
-- and served by the site from /seed/. Technical values are intentionally empty.
-- Running it again changes nothing: existing rows are skipped.

insert into public.fabrics (code, series, color_name, color_family, type, description, is_active, is_placeholder, sort_order) values
${fabrics.map((f) => row([f.code, f.series, f.colorName, f.colorFamily, f.type, f.description, f.isActive, true, f.sortOrder])).join(",\n")}
on conflict (code) do nothing;

insert into public.fabric_textures (fabric_id, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color, derived_maps)
select f.id, v.albedo_1k, v.albedo_2k, v.normal_1k, v.normal_2k, v.roughness_1k, v.roughness_2k, v.thumb, v.repeat_w_cm, v.repeat_h_cm, v.avg_color, false
from (values
${fabrics
  .map((f) => {
    const t = f.texture;
    return row([
      f.code,
      t.maps.albedo["1k"],
      t.maps.albedo["2k"],
      t.maps.normal?.["1k"],
      t.maps.normal?.["2k"],
      t.maps.roughness?.["1k"],
      t.maps.roughness?.["2k"],
      t.thumbUrl,
      t.repeatCm.w,
      t.repeatCm.h,
      t.avgColor,
    ]);
  })
  .join(",\n")}
) as v (code, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color)
join public.fabrics f on f.code = v.code
on conflict (fabric_id) do nothing;

insert into public.models (firm_id, slug, name, procedural_key, fabric_material_names, width_cm, depth_cm, height_cm, default_fabric_code, is_active, sort_order)
select null, v.slug, v.name, v.procedural_key, string_to_array(v.materials, ','), v.w, v.d, v.h, v.fabric, v.active, v.sort_order
from (values
${SEED_MODELS.map((m) =>
  row([
    m.slug,
    m.name,
    m.source.kind === "procedural" ? m.source.generator : null,
    m.fabricMaterialNames.join(","),
    m.dimensionsCm.w,
    m.dimensionsCm.d,
    m.dimensionsCm.h,
    m.defaultFabricCode,
    m.isActive,
    m.sortOrder,
  ]),
).join(",\n")}
) as v (slug, name, procedural_key, materials, w, d, h, fabric, active, sort_order)
where not exists (select 1 from public.models m where m.firm_id is null and m.slug = v.slug);

-- a sample firm page (/f/ornek-mobilya) with a placeholder logo
insert into public.firms (name, slug, logo_path, accent_color, whatsapp, is_active) values
${SEED_FIRMS.map((f) => row([f.name, f.slug, f.logoUrl, f.accentColor, f.whatsapp, f.isActive])).join(",\n")}
on conflict (slug) do nothing;
`;

const out = path.join(process.cwd(), "supabase", "seed.sql");
writeFileSync(out, sql);
console.log(`${out}: ${fabrics.length} kumaş, ${SEED_MODELS.length} model, ${SEED_FIRMS.length} firma`);
