// Writes supabase/kumaslar-misso.sql: the ORMEN fabrics prepared from photos
// (lib/seed/photo-fabrics.ts) as plain SQL for the Supabase SQL editor. The
// images are served by the site itself from /seed/fabrics/…, so only rows are
// added. Safe to run twice: existing codes are skipped.
//
//   npx tsx scripts/build-photo-fabrics-sql.ts

import { writeFileSync } from "node:fs";
import path from "node:path";
import { buildPhotoFabrics } from "../lib/seed/photo-fabrics";

const q = (v: string | number | boolean | null | undefined): string =>
  v === null || v === undefined ? "null" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);
const row = (vals: (string | number | boolean | null | undefined)[]) => `  (${vals.map(q).join(", ")})`;

const fabrics = buildPhotoFabrics();

const sql = `-- ORMEN Atelier: MISSO fabrics from photos. GENERATED by scripts/build-photo-fabrics-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run (after all migrations).
-- Codes follow the order the photos were sent in; colour names and the scale are provisional
-- (see lib/seed/photo-fabrics.ts) and can be changed in the panel. Width, pattern repeat and
-- cut direction are left empty on purpose: they are not known yet.

insert into public.fabrics (code, series, color_name, color_family, type, description, pattern, is_active, is_placeholder, sort_order) values
${fabrics.map((f) => row([f.code, f.series, f.colorName, f.colorFamily, f.type, f.description, f.pattern, f.isActive, false, f.sortOrder])).join(",\n")}
on conflict (code) do nothing;

insert into public.fabric_textures (fabric_id, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color, derived_maps)
select f.id, v.albedo_1k, v.albedo_2k, v.normal_1k, v.normal_2k, v.roughness_1k, v.roughness_2k, v.thumb, v.repeat_w_cm, v.repeat_h_cm, v.avg_color, true
from (values
${fabrics
  .map((f) => {
    const t = f.texture;
    return row([f.code, t.maps.albedo["1k"], t.maps.albedo["2k"], t.maps.normal?.["1k"], t.maps.normal?.["2k"], t.maps.roughness?.["1k"], t.maps.roughness?.["2k"], t.thumbUrl, t.repeatCm.w, t.repeatCm.h, t.avgColor]);
  })
  .join(",\n")}
) as v (code, albedo_1k, albedo_2k, normal_1k, normal_2k, roughness_1k, roughness_2k, thumb, repeat_w_cm, repeat_h_cm, avg_color)
join public.fabrics f on f.code = v.code
on conflict (fabric_id) do nothing;
`;

const out = path.join(process.cwd(), "supabase", "kumaslar-misso.sql");
writeFileSync(out, sql);
console.log(`${out}: ${fabrics.length} kumaş`);
