// Writes supabase/modeller-vitrin.sql: the showcase models (Chester, modern, İskandinav, köşe, U, blok, puf)
// (lib/seed/showcase-models.ts) for the Supabase SQL editor. Safe to run twice.
//
//   npx tsx scripts/build-showcase-sql.ts

import { writeFileSync } from "node:fs";
import path from "node:path";
import { SHOWCASE_MODELS } from "../lib/seed/showcase-models";

const q = (v: string | number | boolean | null | undefined): string =>
  v === null || v === undefined ? "null" : typeof v === "string" ? `'${v.replace(/'/g, "''")}'` : String(v);

const rows = SHOWCASE_MODELS.map((m) => {
  if (m.source.kind !== "parametric") throw new Error(m.slug);
  return `  (${[m.slug, m.name, JSON.stringify(m.source.params), m.fabricMaterialNames.join(","), m.dimensionsCm.w, m.dimensionsCm.d, m.dimensionsCm.h, m.defaultFabricCode, m.isActive, m.sortOrder].map(q).join(", ")})`;
});

const sql = `-- ORMEN Atelier: showcase models (Chester, modern, İskandinav, köşe, U, blok, puf). GENERATED by scripts/build-showcase-sql.ts; do not edit by hand.
-- Paste into the Supabase SQL editor and press Run. Run supabase/kumaslar-misso.sql first (default fabrics).
-- Running it again changes nothing: existing models are skipped.

insert into public.models (firm_id, slug, name, procedural_key, params, fabric_material_names, width_cm, depth_cm, height_cm, default_fabric_code, is_active, sort_order)
select null, v.slug, v.name, 'parametric', v.params::jsonb, string_to_array(v.materials, ','), v.w, v.d, v.h, v.fabric, v.active, v.sort_order
from (values
${rows.join(",\n")}
) as v (slug, name, params, materials, w, d, h, fabric, active, sort_order)
where not exists (select 1 from public.models m where m.firm_id is null and m.slug = v.slug);
`;
const out = path.join(process.cwd(), "supabase", "modeller-vitrin.sql");
writeFileSync(out, sql);
console.log(`${out}: ${SHOWCASE_MODELS.length} model`);
